function skillsMember() {
  return [
    'HTML',
    'CSS',
    'JavaScript',
    'React',
    'Node.js',
    'Python',
    'Django',
    'Ruby',
    'Ruby on Rails',
    'Java',
    'Spring',
    'PHP',
    'Laravel',
    'Swift',
    'Kotlin',
    'C#',
    'ASP.NET',
    'SQL',
    'NoSQL',
    'MongoDB',
    'MySQL',
    'PostgreSQL',
    'AWS',
    'Azure',
    'GCP',
    'Docker',
    'Kubernates',
    'Jenkins',
    'Git',
    'GitHub',
    'GitLab',
    'Bitbucket',
    'JIRA',
    'Slack',
    'Trello',
    'Asana',
    'Figma',
    'Sketch',
    'Photoshop',
    'Illustrator',
    'InDesign',
    'After Effects',
    'Premiere Pro',
    'Final Cut Pro',
    'Logic Pro',
    'Pro Tools',
    'Ableton Live',
    'Unity',
    'Unreal Engine',
    'Blender',
    'Maya',
    'ZBrush',
    'Substance Painter',
    'Substance Designer',
    'Cinema 4D',
    '3ds Max',
    'AutoCAD',
    'Revit',
    'SketchUp',
    'Rhino',
    'Grasshopper',
    'V-Ray',
    'Corona Renderer',
    'Octane Render',
    'Redshift',
    'Arnold',
    'KeyShot',
    'Photoscan',
    'Agisoft Metashape',
    'RealityCapture',
    'Matterport',
    'Cyclone',
    'Leica Geosystems',
    'FARO',
    'Trimble',
    'Topcon',
    'Autodesk',
    'Adobe',
    'Maxon',
    'Pixologic',
    'Allegorithmic',
    'Foundry',
    'Chaos Group',
    'OTOY',
    'Luxion',
    'Agisoft',
    'Matterport',
    'Bentley',
    'Nemetschek',
    'McNeel',
    'Trimble',
    'Hexagon',
    'Leica Geosystems',
    'FARO',
    'Topcon']
}
